import { CheckCircle2, Share, Link, Sparkles } from "lucide-react"

export default function SeoContent() {
  return (
    <section className="py-20 lg:py-24 bg-slate-50 border-t border-slate-200/60">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center">
          {/* Left: What is a URL shortener */}
          <div className="space-y-6">
            <span className="inline-block text-xs font-semibold uppercase tracking-wider text-indigo-600 bg-indigo-50 px-3 py-1 rounded-full">
              Understanding Link Shortening
            </span>
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-slate-900 leading-tight">
              What is a URL Shortener & Why Does It Matter?
            </h2>
            <p className="text-slate-600 text-base leading-relaxed">
              A <strong>URL shortener</strong> is an online tool that translates lengthy web addresses into concise, manageable URLs. Long links often contain tracking query parameters, nested folder hierarchies, and messy character strings that look untrustworthy and eat up precious character space.
            </p>
            <p className="text-slate-600 text-base leading-relaxed">
              When someone clicks a shortened link generated by <strong>BitLinks</strong>, our server receives the request, matches the unique short slug with the original web address stored in our high-performance MongoDB database, and instantly redirects the visitor to the final destination.
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
              <div className="p-4 rounded-xl bg-white border border-slate-200 shadow-sm flex items-start gap-3">
                <CheckCircle2 className="w-5 h-5 text-indigo-600 shrink-0 mt-0.5" />
                <div>
                  <h3 className="font-semibold text-sm text-slate-900">Cleaner Sharing</h3>
                  <p className="text-xs text-slate-500 mt-1">Eliminate broken links caused by accidental wrapping in text messages or emails.</p>
                </div>
              </div>
              <div className="p-4 rounded-xl bg-white border border-slate-200 shadow-sm flex items-start gap-3">
                <CheckCircle2 className="w-5 h-5 text-indigo-600 shrink-0 mt-0.5" />
                <div>
                  <h3 className="font-semibold text-sm text-slate-900">Custom Aliases</h3>
                  <p className="text-xs text-slate-500 mt-1">Brand your links with custom memorable slugs that audience members can type by memory.</p>
                </div>
              </div>
            </div>
          </div>

          {/* Right: Why Use a Short URL Cards */}
          <div className="bg-white rounded-3xl p-8 sm:p-10 border border-slate-200/80 shadow-md space-y-6">
            <h3 className="text-2xl font-bold text-slate-900">
              Why Use BitLinks for Your Links?
            </h3>
            <ul className="space-y-4">
              <li className="flex items-start gap-4">
                <div className="w-8 h-8 rounded-lg bg-indigo-50 text-indigo-600 flex items-center justify-center shrink-0 mt-1">
                  <Share className="w-4 h-4" />
                </div>
                <div>
                  <h4 className="text-base font-semibold text-slate-900">Social Media Friendly</h4>
                  <p className="text-sm text-slate-600 mt-0.5">
                    Perfect for platforms like X (Twitter), Instagram bios, LinkedIn posts, and WhatsApp broadcasts where short, readable links drive higher click-through engagement.
                  </p>
                </div>
              </li>

              <li className="flex items-start gap-4">
                <div className="w-8 h-8 rounded-lg bg-indigo-50 text-indigo-600 flex items-center justify-center shrink-0 mt-1">
                  <Sparkles className="w-4 h-4" />
                </div>
                <div>
                  <h4 className="text-base font-semibold text-slate-900">Professional Presentation</h4>
                  <p className="text-sm text-slate-600 mt-0.5">
                    Clean URLs look professional on resumes, portfolios, slide decks, and marketing collaterals instead of messy raw strings.
                  </p>
                </div>
              </li>

              <li className="flex items-start gap-4">
                <div className="w-8 h-8 rounded-lg bg-indigo-50 text-indigo-600 flex items-center justify-center shrink-0 mt-1">
                  <Link className="w-4 h-4" />
                </div>
                <div>
                  <h4 className="text-base font-semibold text-slate-900">Fast Server-Side Redirects</h4>
                  <p className="text-sm text-slate-600 mt-0.5">
                    Powered by Next.js Server Components and low-latency database queries, ensuring your visitors arrive at your target webpage without noticeable delay.
                  </p>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  )
}
